// Generated by github.com/davyxu/tabtoy
// DO NOT EDIT!!
// Version: 3.1.4
package data

import "errors"

type TableEnumValue struct {
	Name  string
	Index int32
}

type AType int32

const (
	AType_SJBCrazy     = 15 // 世界杯狂欢
	AType_NewYearCrazy = 16 // 新春狂欢
)

var (
	ATypeEnumValues = []TableEnumValue{
		{Name: "SJBCrazy", Index: 15},     // 世界杯狂欢
		{Name: "NewYearCrazy", Index: 16}, // 新春狂欢
	}
	ATypeMapperValueByName = map[string]int32{}
	ATypeMapperNameByValue = map[int32]string{}
)

func (self AType) String() string {
	name, _ := ATypeMapperNameByValue[int32(self)]
	return name
}

type MyData struct {
	ID   int32  `tb_name:"ID"`
	Name string `tb_name:"名称"`
}

// Combine struct
type Table struct {
	MyData []*MyData // table: MyData

	// Indices

	// Handlers
	postHandlers []func(*Table) error `json:"-"`
	preHandlers  []func(*Table) error `json:"-"`

	indexHandler map[string]func() `json:"-"`
	resetHandler map[string]func() `json:"-"`
}

// 注册加载后回调(用于构建数据)
func (self *Table) RegisterPostEntry(h func(*Table) error) {

	if h == nil {
		panic("empty postload handler")
	}

	self.postHandlers = append(self.postHandlers, h)
}

// 注册加载前回调(用于清除数据)
func (self *Table) RegisterPreEntry(h func(*Table) error) {

	if h == nil {
		panic("empty preload handler")
	}

	self.preHandlers = append(self.preHandlers, h)
}

// 清除索引和数据
func (self *Table) ResetData() error {

	err := self.InvokePreHandler()
	if err != nil {
		return err
	}

	return self.ResetTable("")
}

// 全局表构建索引及通知回调
func (self *Table) BuildData() error {

	err := self.IndexTable("")
	if err != nil {
		return err
	}

	return self.InvokePostHandler()
}

// 调用加载前回调
func (self *Table) InvokePreHandler() error {
	for _, h := range self.preHandlers {
		if err := h(self); err != nil {
			return err
		}
	}

	return nil
}

// 调用加载后回调
func (self *Table) InvokePostHandler() error {
	for _, h := range self.postHandlers {
		if err := h(self); err != nil {
			return err
		}
	}

	return nil
}

// 为表建立索引. 表名为空时, 构建所有表索引
func (self *Table) IndexTable(tableName string) error {

	if tableName == "" {

		for _, h := range self.indexHandler {
			h()
		}
		return nil

	} else {
		if h, ok := self.indexHandler[tableName]; ok {
			h()
		}

		return nil
	}
}

// 重置表格数据
func (self *Table) ResetTable(tableName string) error {
	if tableName == "" {
		for _, h := range self.resetHandler {
			h()
		}

		return nil
	} else {
		if h, ok := self.resetHandler[tableName]; ok {
			h()
			return nil
		}

		return errors.New("reset table failed, table not found: " + tableName)
	}
}

// 初始化表实例
func NewTable() *Table {

	self := &Table{
		indexHandler: make(map[string]func()),
		resetHandler: make(map[string]func()),
	}

	self.indexHandler["MyData"] = func() {

	}

	self.resetHandler["MyData"] = func() {
		self.MyData = nil

	}

	self.ResetData()

	return self
}

func init() {

	for _, v := range ATypeEnumValues {
		ATypeMapperValueByName[v.Name] = v.Index
		ATypeMapperNameByValue[v.Index] = v.Name
	}

}
